name: Build Store Android App (Expo)
on:
  release:
    types: [published]
jobs:
  publish:
    name: Build Store Android App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: |
          VARIANT=store
          sed -i s/appvariant/${VARIANT}/g app.json
          echo "VERSION=0.${{ github.run_number }}" > .env
          cat configuration/default.env >> .env
          cat configuration/${VARIANT}.env >> .env
          echo "Using environment:" && cat .env
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_USERNAME }}
          expo-password: ${{ secrets.EXPO_PASSWORD }}
      - run: yarn install
      - run: expo build:android --generate-keystore
