name: Build and deploy store web app
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and Deploy Store Web App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
      - run: |
          VARIANT=store
          sed -i s/appvariant/${VARIANT}/g app.json
          echo "VERSION=0.${{ github.run_number }}" > .env
          cat configuration/default.env >> .env
          cat configuration/${VARIANT}.env >> .env
          echo "Using environment:" && cat .env
      - run: yarn install
      - run: expo build:web
      - uses: appleboy/scp-action@master
        with:
          source: web-build
          target: web-build-store-${{ github.run_id }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mv -f htdocs-store www-store-old
            mv -f web-build-store-${{ github.run_id }} htdocs-store 
            rm -rf www-store-old 